import "./globals.css";
import { Roboto } from "next/font/google";

import Header from "components/Header";
import Footer from "components/Footer";

const roboto = Roboto({
	weight: ["100", "300", "400", "500", "700", "900"],
	subsets: ["latin"],
	display: "swap",
});

export const metadata = {
	title: "Alecon Engenharia",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="pt-br">
			<body className={roboto.className}>
				<Header />
				<main>{children}</main>
        <Footer />
			</body>
		</html>
	);
}
